"use client";
import './globals.css';
import {AppProvider} from "react-application";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider shape={{}}>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
