"use client";
import * as React from "react";
import './globals.css';
import {AppProvider} from "react-promise-cache";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <AppProvider>
      <React.Suspense fallback="Loading your app">
        {children}
      </React.Suspense>
    </AppProvider>
    </body>
    </html>
  )
}
